"""Added tag column

Revision ID: 4325e9697e70
Revises: c2ce2002f947
Create Date: 2020-12-30 19:33:36.690320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4325e9697e70'
down_revision = 'c2ce2002f947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('tag', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'tag')
    # ### end Alembic commands ###
